POST http://localhost:8000/register
Content-Type: application/json

{
  "username": "moshu12345",
  "password": "123qwe123",
  "email": "e12345@domain.ro"
}
#######
GET http://localhost:8000/login?username=moshu123456&password=123qwe123

#######
GET http://localhost:8000/asset?pageSize=5&pageNumber=4

#######
GET http://localhost:8000/asset/60856401f3e651d01d9c2927

#######
GET http://localhost:8000/link/60856401f3e651d01d9c2927

#######
POST http://localhost:8000/asset
Content-Type: application/json

{
  "children": [1,2,3],
  "description": "",
  "group": "",
  "name": "Asset21",
  "observation": "",
  "parent": 13,
  "serialNumber": "",
  "size": "",
  "yearOfProduct": ""
}
